<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">loadCache</value>
  <value name="encodeutf8">true</value>
  <value name="body">Ly8gcGlwZWxpbmUNCklEYXRhQ3Vyc29yIHBpcGVsaW5lQ3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vy
c29yKCk7DQoJU3RyaW5nCXNjcmlwdCA9IElEYXRhVXRpbC5nZXRTdHJpbmcoIHBpcGVsaW5lQ3Vy
c29yLCAic2NyaXB0IiApOw0KCQ0KDQoNClNjcmlwdEVuZ2luZU1hbmFnZXIgZmFjdG9yeSA9IG5l
dyBTY3JpcHRFbmdpbmVNYW5hZ2VyKCk7DQpTY3JpcHRFbmdpbmUgZW5naW5lID0gZmFjdG9yeS5n
ZXRFbmdpbmVCeU5hbWUoIkphdmFTY3JpcHQiKTsNCg0KDQoNCmlmKHNjcmlwdCE9bnVsbCl7DQoJ
DQoJU3RyaW5nUmVhZGVyIHJlYWRlciA9IG51bGw7DQoJdHJ5IHsNCgkJDQoJCXJlYWRlciA9IG5l
dyBTdHJpbmdSZWFkZXIoc2NyaXB0KTsNCgkJDQoJCQ0KDQoJCQ0KDQoJCS8vIHBpcGVsaW5lDQoJ
CUlEYXRhQ3Vyc29yIHBpcGVsaW5lQ3Vyc29yXzEgPSBwaXBlbGluZS5nZXRDdXJzb3IoKTsNCgkJ
T2JqZWN0IHNjcmlwdE9iaiA9IG5ldyBPYmplY3QoKTsNCgkJSURhdGFVdGlsLnB1dCggcGlwZWxp
bmVDdXJzb3JfMSwgInNjcmlwdE9iaiIsIGVuZ2luZS5ldmFsKHJlYWRlcikgKTsNCgkJcGlwZWxp
bmVDdXJzb3JfMS5kZXN0cm95KCk7DQoNCgkJDQoJfSBjYXRjaCAoRXhjZXB0aW9uIGUpIHsNCgkJ
Ly8gVE9ETzogaGFuZGxlIGV4Y2VwdGlvbg0KCX0NCn0NCg0KCQ==</value>
</Values>
