<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">doParallelThreadInvoke</value>
  <value name="encodeutf8">true</value>
  <value name="body">Ly8gcGlwZWxpbmUNCgkJLy9JRGF0YUN1cnNvciBwaXBlbGluZWN1cnNvciA9IHBpcGVsaW5lLmdl
dEN1cnNvcigpOw0KCQkNCgkNCg0KLy8gcGlwZWxpbmUNCklEYXRhQ3Vyc29yIHBpcGVsaW5lQ3Vy
c29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoJU3RyaW5nCWNvdW50ID0gSURhdGFVdGlsLmdl
dFN0cmluZyggcGlwZWxpbmVDdXJzb3IsICJjb3VudCIgKTsNCnBpcGVsaW5lQ3Vyc29yLmRlc3Ry
b3koKTsNCg0KLy8gcGlwZWxpbmUNCg0KCQ0KZm9yIChpbnQgaSA9IDA7IGkgPCBJbnRlZ2VyLnBh
cnNlSW50KGNvdW50KTsgaSsrKSB7DQoNCglTZXJ2aWNlLmRvVGhyZWFkSW52b2tlKCJCdXNpbmVz
c0ZpZWxkc1ZhbGlkYXRvci50ZXN0IiwgInRlc3RYTUwiLFNlcnZpY2UuZ2V0U2Vzc2lvbigpLElE
YXRhVXRpbC5jbG9uZShwaXBlbGluZSkpOw0KfQ0KDQoJ</value>
</Values>
